version: '3.8'

services:
  grafana-line-proxy:
    build: .
    container_name: grafana-line-proxy
    ports:
      - "9080:3000" # 對外開放 9080 port，Grafana Webhook 請填入此 port
    networks:
      - monitor
    # environment:
      # - PORT=3000
      # 請替換為你的 LINE Bot Channel Access Token
      # - LINE_ACCESS_TOKEN=your_channel_access_token
      # 請替換為你的 LINE Bot Channel 安全驗證碼
      # - LINE_CHANNEL_SECRET=your_channel_secret
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -q --spider http://localhost:3000/health || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
networks:
  monitor:
    external: true #認為已經存在，不用建立