version: '3.8'

services:
  grafana-line-proxy:
    build: .
    container_name: grafana-line-proxy
    ports:
      - "9080:3000" # 對外開放 9080 port，Grafana Webhook 請填入此 port
    networks:
      - monitor
    environment:
      - PORT=3000
      # 請替換為你的 LINE Bot Channel Access Token
      - LINE_ACCESS_TOKEN=9YYvKz4ezNSgOFFjGAWGJzUZMXGcI0X8JKqTJSdr1ybkQW6S1kmv2iK0Xj2nMb+E58bHsoAVigRC3T4qDf6z/HJsTNT3vmLoqEI5vlbK9wKakAW8AuEHs2ikaprj7pM7uE54jW9wPIpBXXO/vcqXxAdB04t89/1O/w1cDnyilFU=
      # 請替換為你的 LINE Bot Channel 安全驗證碼
      - LINE_CHANNEL_SECRET=your_channel_secret
    restart: unless-stopped
networks:
  monitor:
    external: true #認為已經存在，不用建立